const INCORRECT_DATA_ERROR_CODE = 400;
const NOTFOUND_ERROR_CODE = 404;
const SERVER_ERROR_CODE = 500;
const CONFLICT_ERROR_CODE = 409;
const FORBIDDEN_ERROR_CODE = 403;
const UNAUTHORIZED_ERROR_CODE = 401;

const HTTP_REGEX = /https?:\/\/(www\.)?[-a-zA-Z0-9.-]{2,256}\.[a-zA-Z0-9]{2,4}\b(\/[-a-zA-Z0-9@:%_+~#?&=]*)?/;

module.exports = {
  INCORRECT_DATA_ERROR_CODE,
  NOTFOUND_ERROR_CODE,
  SERVER_ERROR_CODE,
  CONFLICT_ERROR_CODE,
  FORBIDDEN_ERROR_CODE,
  UNAUTHORIZED_ERROR_CODE,
  HTTP_REGEX,
};
